### ISSUE TITLE
We need a API first

### ISSUE THREAD

**Issue by radioblahaj** [ScratchUtilities/gobo.chrome#1]
They are Many Options for a API

- Paid 
- Free

There is a Free one called [Shetty](https://www.producthunt.com/posts/sheety)

**Comment by radioblahaj** [comment]
Here is a Example of https://github.com/abhijithvijayan/kutt-extension A Link Shrothner API For Kutt.

It's a Cross Browser Extestion for Firefox and Chrome

**Comment by sweezyio** [comment]
I don't think we would need an API, we can just run it through the current calculation to convert it to our format. The extension could also make the redirection faster by having the conversion from our format to the actual format done locally instead of through the actual website.

**Comment by radioblahaj** [comment]
Alright, I'll get started on this
