### ISSUE TITLE
Extensions are banned from being advertised on scratch.

### ISSUE THREAD

**Issue by Andreto** [ScratchUtilities/gobo.chrome#2]
https://scratch.mit.edu/discuss/topic/284272/
I ran into this problem with another project I was working on. We could probably advertise it on the gobo.cf site tough.

**Comment by sweezyio** [comment]
Yea, as long as we aren't advertising on Scratch we should be fine.

**Comment by sweezyio** [comment]
I'm gonna close this, but if any more information comes along feel free to reopen it.

**Comment by radioblahaj** [comment]
This should be fine as this a Link shronter Nothign else
